FROM postgres:latest

ARG PG_DEV_VERSION=14

COPY ./data/*.csv ./
COPY db.sql /docker-entrypoint-initdb.d/
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d/
RUN chown -R postgres:postgres *.csv
