version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile.pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raily
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.front
  #   ports:
  #     - 3000:3000
  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.back
  #   ports:
  #     - 4000:4000
